<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="hexapod_robot">
  
  <!-- 包含Gazebo和ros2_control的宏定义 -->
  <xacro:include filename="$(find hexapod_description)/urdf/hexapod.gazebo.xacro"/>
  <xacro:include filename="$(find hexapod_description)/urdf/hexapod.ros2_control.xacro"/>
  
  <!-- 材料定义 -->
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>
  <material name="orange">
    <color rgba="1.0 0.5 0.0 1.0"/>
  </material>
  <material name="white">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>
  
  <!-- 基础参数 -->
  <xacro:property name="body_length" value="0.4"/>
  <xacro:property name="body_width" value="0.3"/>
  <xacro:property name="body_height" value="0.1"/>
  <xacro:property name="body_mass" value="5.0"/>
  
  <!-- 腿部参数 -->
  <xacro:property name="coxa_length" value="0.08"/>
  <xacro:property name="femur_length" value="0.15"/>
  <xacro:property name="tibia_length" value="0.15"/>
  <xacro:property name="leg_radius" value="0.02"/>
  
  <!-- 主体 -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${body_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </link>
  
  
  <!-- 腿部宏定义 -->
  <xacro:macro name="leg" params="leg_id side x_pos y_pos coxa_angle">
    
    <!-- Coxa关节 -->
    <joint name="coxa_${leg_id}_joint" type="revolute">
      <parent link="base_link"/>
      <child link="coxa_${leg_id}_link"/>
      <origin xyz="${x_pos} ${y_pos} -${body_height/2}" rpy="0 0 ${coxa_angle}"/>
      <axis xyz="0 0 1"/>
      <limit lower="${-1.57}" upper="${1.57}" effort="10" velocity="5"/>
    </joint>
    
    <link name="coxa_${leg_id}_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${leg_radius}" length="${coxa_length}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${leg_radius}" length="${coxa_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    </link>
    
    <!-- Femur关节 -->
    <joint name="femur_${leg_id}_joint" type="revolute">
      <parent link="coxa_${leg_id}_link"/>
      <child link="femur_${leg_id}_link"/>
      <origin xyz="${coxa_length/2} 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-2.0}" upper="${2.0}" effort="10" velocity="5"/>
    </joint>
    
    <link name="femur_${leg_id}_link">
      <visual>
        <origin xyz="${femur_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${leg_radius}" length="${femur_length}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="${femur_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${leg_radius}" length="${femur_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.2"/>
        <origin xyz="${femur_length/2} 0 0"/>
        <inertia ixx="0.002" ixy="0.0" ixz="0.0" iyy="0.002" iyz="0.0" izz="0.002"/>
      </inertial>
    </link>
    
    <!-- Tibia关节 -->
    <joint name="tibia_${leg_id}_joint" type="revolute">
      <parent link="femur_${leg_id}_link"/>
      <child link="tibia_${leg_id}_link"/>
      <origin xyz="${femur_length} 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-2.5}" upper="${0.5}" effort="10" velocity="5"/>
    </joint>
    
    <link name="tibia_${leg_id}_link">
      <visual>
        <origin xyz="${tibia_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${leg_radius}" length="${tibia_length}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="${tibia_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${leg_radius}" length="${tibia_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.15"/>
        <origin xyz="${tibia_length/2} 0 0"/>
        <inertia ixx="0.0015" ixy="0.0" ixz="0.0" iyy="0.0015" iyz="0.0" izz="0.0015"/>
      </inertial>
    </link>
    
    <!-- 足端 -->
    <joint name="foot_${leg_id}_joint" type="fixed">
      <parent link="tibia_${leg_id}_link"/>
      <child link="foot_${leg_id}_link"/>
      <origin xyz="${tibia_length} 0 0" rpy="0 0 0"/>
    </joint>
    
    <link name="foot_${leg_id}_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="0.03"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="0.03"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.05"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
      </inertial>
    </link>
    
  </xacro:macro>
  
  <!-- 创建6条腿 -->
  <!-- 左侧3条腿 -->
  <xacro:leg leg_id="1" side="left" x_pos="${body_length/2 - 0.05}" y_pos="${body_width/2 + 0.03}" coxa_angle="0.0"/>
  <xacro:leg leg_id="2" side="left" x_pos="0.0" y_pos="${body_width/2 + 0.05}" coxa_angle="0.0"/>
  <xacro:leg leg_id="3" side="left" x_pos="${-body_length/2 + 0.05}" y_pos="${body_width/2 + 0.03}" coxa_angle="0.0"/>
  
  <!-- 右侧3条腿 -->
  <xacro:leg leg_id="4" side="right" x_pos="${body_length/2 - 0.05}" y_pos="${-(body_width/2 + 0.03)}" coxa_angle="0.0"/>
  <xacro:leg leg_id="5" side="right" x_pos="0.0" y_pos="${-(body_width/2 + 0.05)}" coxa_angle="0.0"/>
  <xacro:leg leg_id="6" side="right" x_pos="${-(body_length/2 - 0.05)}" y_pos="${-(body_width/2 + 0.03)}" coxa_angle="0.0"/>
  
  <!-- 包含Gazebo和ros2_control插件 -->
  <xacro:hexapod_gazebo/>
  <xacro:hexapod_ros2_control/>
  
</robot>

